default_stages: [ commit, push ]

repos:
  - repo: local
    hooks:
      - id: pyupgrade
        name: pyupgrade
        entry: poetry run pyupgrade
        types: [ python ]
        language: system

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black .
        types: [ python ]
        language: system

  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: poetry run isort --settings-path pyproject.toml
        types: [ python ]
        language: system
