version: '3.7'

networks:
  loki:

services:
  app:
    container_name: "app_python"
    image: 41694/dovops_lab1:latest
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"
    ports:
      - '8080:8080'
    networks:
      - loki

  loki:
    container_name: "prometheus.loki"
    image: grafana/loki:1.6.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yml:/etc/loki-config.yml
    command: -config.file=/etc/loki/local-config.yaml -print-config-stderr=true
    networks:
      - loki

  promtail:
    container_name: "prometheus.promtail"
    image: grafana/promtail:1.6.0
    volumes:
      - /var/lib/docker/containers/:/var/lib/docker/containers
      - ./promtail/promtail-config.yml:/etc/promtail/docker-config.yml
    command: -config.file=/etc/promtail/docker-config.yml
    networks:
      - loki

  grafana:
    container_name: "prometheus.grafana"
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - loki

  prometheus:
    image: prom/prometheus:v2.29.0
    container_name: "monitoring.prometheus"
    volumes:
      - ./prometheus/prometheus-config.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - loki

volumes:
  grafana-data: { }
