kind: Deployment
apiVersion: apps/v1
metadata:
  name: app
  namespace: default
  labels:
    app: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: devops-lab1-k59fb
          image: 41694/devops_lab1
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 125m
              memory: 128Mi
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
