kind: Service
apiVersion: v1
metadata:
  name: app
  namespace: default
  labels:
    app: app
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 32012
  selector:
    app: app
  type: LoadBalancer
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
status:
  loadBalancer: { }
