pipeline {
    agent { docker { image 'python:3.8-alpine' } }
    stages {
        stage('build') {
            steps {
                sh "python3 -m venv /venv && make install PYTHON=/venv/bin/python3"
            }
        }
        stage('test'){
            steps {
                sh "pushd .."
                sh "make test"
                sh "popd"
            }
        }
    }
}
