pipeline {
  agent any
  stages {
    stage("Build"){
        agent {
            docker {
                image '41694/devops_lab1'
            }
        }
    }
    stage('Linting') { // Run pylint against your code
      steps {
        script {
          sh """
          make lint
          """
        }
      }
    }
    stage('Unit Testing') { // Perform unit testing
      steps {
        script {
          sh """
          make test
          """
        }
      }
    }
  }
}
