pipeline {
  agent {
    dockerfile{
        image 'python:3.8-alpine'
    }
  }
  stages {  // Define the individual processes, or stages, of your CI pipeline
    stage('Install dependencies'){
      steps {
       script {
         sh """
          python3 -m venv /venv && make install PYTHON=/venv/bin/python3
          """
         }
       }
    }
    stage('Linting') { // Run pylint against your code
      steps {
        script {
          sh """
          make lint
          """
        }
      }
    }
    stage('Unit Testing') { // Perform unit testing
      steps {
        script {
          sh """
          make test
          """
        }
      }
    }
  }
}
