- name: 'Create destination directory'
  file:
    path: "{{ app_directory }}"
    state: directory
    mode: 0644

- name: 'Copy docker-compose files'
  copy:
    src: templates/{{ item }}
    dest: "{{ app_directory }}/{{ item }}"
    mode: 0644
  loop:
    - docker-compose.yml

- name: install pip3
  apt: name=python3-pip state=present

- name: Install python-docker
  pip:
    name: docker-compose

- name: 'Up docker-compose'
  docker_compose:
    project_src: "{{  app_directory  }}"
