- name: 'Install docker dependencies'
  apt:
    name: '{{ item }}'
    state: 'present'
  with_items:
    - 'apt-transport-https'
    - 'ca-certificates'

- name: 'Add docker repo apt key'
  apt_key:
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    id: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
    state: 'present'
  register: 'add_repository_key'
  ignore_errors: true

- name: 'Add Docker repository'
  apt_repository:
    repo: '{{ docker_apt_repository }}'
    state: 'present'
    update_cache: 'yes'

- name: 'Install docker'
  apt:
    name: 'docker-ce={{ docker_version }}'
    state: 'present'

- name: 'Enable docker systemd service'
  service:
    name: 'docker'
    state: 'started'
    enabled: 'yes'
